"""Deterministic risk classification for guarded workspace file changes.

This module classifies already-generated guarded workspace patches. It does not
approve, block, or apply patches. Later M1 issues use these machine-readable
file risk reasons for summaries, approval prompts, blocking, and audit.
"""

from __future__ import annotations

import fnmatch
import json
import re
import shutil
import subprocess  # nosec B404
from collections import Counter
from collections.abc import Callable, Iterable
from dataclasses import dataclass
from functools import cached_property
from pathlib import Path, PurePosixPath

from rygnal.changed_files import ChangedFileKind, normalize_repo_relative_path
from rygnal.dependency_governance import (
    DependencyGovernancePlan,
    WorkspaceDependencyTarget,
    build_dependency_governance_plan,
)
from rygnal.diff_limits import (
    DEFAULT_DIFF_LIMIT_POLICY,
    DiffLimitPolicy,
    DiffLimitReason,
    evaluate_diff_limits,
)
from rygnal.patch_diff import PatchDiff, PatchFileDiff
from rygnal.risk_engine import RiskLevel

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - Python < 3.11 compatibility
    try:
        import tomli as tomllib
    except ModuleNotFoundError:  # pragma: no cover - project runtime is Python 3.11+
        tomllib = None
from rygnal.rust_kernel import (
    RustCriticalityAssessment,
    RustCriticalityEvaluationError,
    RustCriticalityInput,
    RustKernelError,
    RustKernelUnavailableError,
    evaluate_criticality,
)

RISK_LEVEL_ORDER: dict[RiskLevel, int] = {
    RiskLevel.LOW: 0,
    RiskLevel.MEDIUM: 1,
    RiskLevel.HIGH: 2,
    RiskLevel.CRITICAL: 3,
}

RUST_CRITICALITY_ENFORCED_LEVELS: dict[str, RiskLevel] = {
    "high": RiskLevel.HIGH,
    # Rust criticality is an approval signal in the Python guarded runner.
    # It must not independently create a BLOCKED guarded-run status.
    "critical": RiskLevel.HIGH,
}

MIN_ENFORCED_CRITICALITY_INDEX = 5.0
MAX_CRITICALITY_SHADOW_BYTES = 1_000_000
MAX_CRITICALITY_RAW_BYTES = MAX_CRITICALITY_SHADOW_BYTES * 2

GIT_SUBMODULE_MODE = "160000"
GIT_SYMLINK_MODE = "120000"
GIT_LFS_POINTER_PREFIX = b"version https://git-lfs.github.com/spec/v1"

CRITICALITY_NOTEBOOK_EXTENSIONS = {".ipynb"}

CRITICALITY_LOCKFILE_NAMES = {
    "bun.lockb",
    "cargo.lock",
    "composer.lock",
    "gemfile.lock",
    "go.sum",
    "gradle.lockfile",
    "package-lock.json",
    "pipfile.lock",
    "pnpm-lock.yaml",
    "poetry.lock",
    "pubspec.lock",
    "uv.lock",
    "yarn.lock",
}

BYPASS_VERDICT_BYPASSED = "bypassed"
BYPASS_VERDICT_RUST_INVOKED = "rust-invoked"
BYPASS_VERDICT_ELEVATED_RISK = "elevated-risk"

BYPASS_REASON_NOT_CANDIDATE = "not-bypass-candidate"
BYPASS_REASON_LOCKFILE_PATH_VALID = "lockfile-root-path-valid"
BYPASS_REASON_LOCKFILE_NESTED_PATH = "rust-invoked:lockfile-nested-path"
BYPASS_REASON_LOCKFILE_INVALID_STRUCTURE = "lockfile-claim-invalid-structure"
BYPASS_REASON_LOCKFILE_ROOT_VALID_JSON = "bypassed:lockfile-root-valid-json"
BYPASS_REASON_LOCKFILE_ROOT_VALID_TOML = "bypassed:lockfile-root-valid-toml"
BYPASS_REASON_PARSE_FAILED_EMPTY = "parse-failed-empty"
BYPASS_REASON_PARSE_FAILED_JSON = "parse-failed-json"
BYPASS_REASON_PARSE_FAILED_TOML = "parse-failed-toml"
BYPASS_REASON_PARSE_FAILED_PATTERN = "parse-failed-pattern"
BYPASS_REASON_SHAPE_MISMATCH_JSON = "shape-mismatch-json"
BYPASS_REASON_SHAPE_MISMATCH_TOML = "shape-mismatch-toml"
BYPASS_REASON_GENERATED_VALID = "bypassed:generated-marker-and-path"
BYPASS_REASON_GENERATED_MARKER_WITHOUT_PATH = "rust-invoked:generated-marker-without-path"
BYPASS_REASON_GENERATED_PATH_WITHOUT_MARKER = "rust-invoked:generated-path-without-marker"

CRITICALITY_GENERATED_MARKERS = (
    "@generated",
    "auto-generated",
    "autogenerated",
    "do not edit",
)


DOC_EXTENSIONS = {
    ".adoc",
    ".md",
    ".rst",
    ".txt",
}

DOC_FILE_NAMES = {
    "changelog",
    "code_of_conduct",
    "contributing",
    "license",
    "readme",
    "security",
}

SOURCE_EXTENSIONS = {
    ".c",
    ".cc",
    ".cpp",
    ".cs",
    ".css",
    ".go",
    ".html",
    ".java",
    ".js",
    ".jsx",
    ".kt",
    ".mjs",
    ".php",
    ".py",
    ".rb",
    ".rs",
    ".scala",
    ".swift",
    ".ts",
    ".tsx",
}

SCRIPT_EXTENSIONS = {
    ".bash",
    ".bat",
    ".cmd",
    ".fish",
    ".ps1",
    ".sh",
    ".zsh",
}

BINARY_EXTENSIONS = {
    ".bin",
    ".class",
    ".dll",
    ".dylib",
    ".exe",
    ".jar",
    ".o",
    ".pyc",
    ".so",
    ".wasm",
    ".war",
}

DEPENDENCY_FILE_NAMES = {
    "build.gradle",
    "cargo.lock",
    "cargo.toml",
    "composer.json",
    "composer.lock",
    "gemfile",
    "gemfile.lock",
    "go.mod",
    "go.sum",
    "gradle.lockfile",
    "package-lock.json",
    "package.json",
    "pipfile",
    "pipfile.lock",
    "pnpm-lock.yaml",
    "poetry.lock",
    "pom.xml",
    "pubspec.lock",
    "pubspec.yaml",
    "pyproject.toml",
    "requirements.txt",
    "uv.lock",
    "yarn.lock",
}

DEPENDENCY_NAME_PATTERNS = (
    "requirements-*.txt",
    "requirements_*.txt",
    "requirements*.in",
    "requirements*.txt",
)

CI_PATH_PATTERNS = (
    ".circleci/*",
    ".github/actions/*",
    ".github/workflows/*",
    ".gitlab-ci.yml",
    "azure-pipelines.yml",
    "bitbucket-pipelines.yml",
    "buildkite.yml",
    "jenkinsfile",
)

INFRA_PATH_PATTERNS = (
    ".dockerignore",
    ".gitignore",
    "docker-compose*.yaml",
    "docker-compose*.yml",
    "dockerfile",
    "helm/*",
    "k8s/*",
    "kubernetes/*",
    "makefile",
    "mkdocs.yml",
    "terraform/*",
    "tox.ini",
    "*.tf",
)

SECURITY_SENSITIVE_PATH_PATTERNS = (
    ".aws/*",
    ".aws/credentials",
    ".azure/*",
    ".config/gcloud/*",
    ".docker/config.json",
    ".env",
    ".env.*",
    ".gnupg/*",
    ".netrc",
    ".npmrc",
    ".pypirc",
    ".ssh/*",
    ".ssh/config",
    ".ssh/id_*",
    "*/.aws/*",
    "*/.aws/credentials",
    "*/.azure/*",
    "*/.config/gcloud/*",
    "*/.docker/config.json",
    "*/.env",
    "*/.env.*",
    "*/.gnupg/*",
    "*/.netrc",
    "*/.npmrc",
    "*/.pypirc",
    "*/.ssh/*",
    "*/.ssh/config",
    "*/.ssh/id_*",
    "*/credentials",
    "*/credentials.*",
    "*/credentials*.json",
    "*/id_dsa",
    "*/id_ecdsa",
    "*/id_ed25519",
    "*/id_rsa",
    "*/private*.key",
    "*/private*.pem",
    "*/secret",
    "*/secret.*",
    "*/secrets",
    "*/secrets.*",
    "*/service-account*.json",
    "*/service_account*.json",
    "*.key",
    "*.p12",
    "*.pem",
    "*.pfx",
    "credentials",
    "credentials.*",
    "credentials*.json",
    "id_dsa",
    "id_ecdsa",
    "id_ed25519",
    "id_rsa",
    "secret",
    "secret.*",
    "secrets",
    "secrets.*",
)

AUTH_SECURITY_PATH_SEGMENTS = {
    "auth",
    "authentication",
    "iam",
    "jwt",
    "oauth",
    "permission",
    "permissions",
    "rbac",
    "security",
    "session",
    "sessions",
}

DEPLOY_PATH_SEGMENTS = {
    "deploy",
    "deployment",
    "deployments",
    "helm",
    "k8s",
    "kubernetes",
    "terraform",
}

SCRIPT_PATH_SEGMENTS = {
    "bin",
    "script",
    "scripts",
    "tool",
    "tools",
}

SECRET_ADDED_LINE_PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("private-key-header", re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----")),
    ("aws-access-key-id", re.compile(r"\bAKIA[0-9A-Z]{16}\b")),
    ("openai-api-key", re.compile(r"\bsk-[A-Za-z0-9_-]{20,}\b")),
    (
        "credential-assignment",
        re.compile(
            r"(?i)\b(api[_-]?key|access[_-]?token|auth[_-]?token|password|"
            r"private[_-]?key|secret|client[_-]?secret)\b\s*[:=]\s*['\"]?[^'\"\s]{8,}"
        ),
    ),
)

DESTRUCTIVE_ADDED_LINE_PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("recursive-force-delete", re.compile(r"(?i)\brm\s+-[a-z]*r[a-z]*f[a-z]*\b")),
    ("world-writable-permission", re.compile(r"(?i)\bchmod\s+777\b")),
    ("pipe-to-shell", re.compile(r"(?i)\b(curl|wget)\b.+\|\s*(sh|bash)\b")),
    ("disk-format", re.compile(r"(?i)\bmkfs(\.|\\s)")),
    ("raw-disk-write", re.compile(r"(?i)\bdd\s+.*\bof=/dev/")),
)


class ChangeRiskClassificationError(RuntimeError):
    """Raised when guarded change risk classification cannot complete safely."""


class _CriticalityInvalidEncodingError(ChangeRiskClassificationError):
    """Raised when file content cannot be decoded as strict UTF-8."""


class _CriticalityGitLfsPointerError(ChangeRiskClassificationError):
    """Raised when file content is a Git LFS pointer instead of real source."""


@dataclass(frozen=True)
class CriticalityBypassVerdict:
    """Deterministic verdict for a claimed Rust criticality bypass."""

    allowed: bool
    reason_code: str
    verdict: str
    is_candidate: bool = True


@dataclass(frozen=True)
class ChangeRiskReason:
    """One deterministic reason for a file or report risk classification."""

    code: str
    risk_level: RiskLevel
    reason: str
    evidence: tuple[tuple[str, object], ...] = ()

    @cached_property
    def audit_summary(self) -> dict[str, object]:
        return {
            "code": self.code,
            "risk_level": self.risk_level.value,
            "reason": self.reason,
            "evidence": dict(self.evidence),
        }


@dataclass(frozen=True)
class RustCriticalityShadow:
    """Observe-only Rust criticality result attached to file risk output."""

    available: bool
    criticality_index: float | None = None
    risk_level: str | None = None
    reasons: tuple[str, ...] = ()
    semantic_metrics: dict[str, object] | None = None
    path_category: str | None = None
    path_severity: str | None = None
    error_code: str | None = None
    error_reason: str | None = None
    criticality_bypass_verdict: str | None = None
    criticality_bypass_reason: str | None = None

    @cached_property
    def audit_summary(self) -> dict[str, object]:
        return {
            "available": self.available,
            "criticality_index": self.criticality_index,
            "risk_level": self.risk_level,
            "reasons": self.reasons,
            "semantic_metrics": self.semantic_metrics,
            "path_category": self.path_category,
            "path_severity": self.path_severity,
            "error_code": self.error_code,
            "error_reason": self.error_reason,
            "criticality_bypass_verdict": self.criticality_bypass_verdict,
            "criticality_bypass_reason": self.criticality_bypass_reason,
        }


@dataclass(frozen=True)
class FileRiskClassification:
    """Risk classification for one changed guarded-workspace file."""

    path: str
    kind: ChangedFileKind
    risk_level: RiskLevel
    reasons: tuple[ChangeRiskReason, ...]
    additions: int | None = None
    deletions: int | None = None
    binary: bool = False
    old_path: str | None = None
    old_mode: str | None = None
    new_mode: str | None = None
    mode_changed: bool = False
    rust_criticality: RustCriticalityShadow | None = None

    @cached_property
    def audit_summary(self) -> dict[str, object]:
        return {
            "path": self.path,
            "old_path": self.old_path,
            "kind": self.kind.value,
            "risk_level": self.risk_level.value,
            "additions": self.additions,
            "deletions": self.deletions,
            "binary": self.binary,
            "old_mode": self.old_mode,
            "new_mode": self.new_mode,
            "mode_changed": self.mode_changed,
            "reasons": tuple(reason.audit_summary for reason in self.reasons),
            "rust_criticality": (
                self.rust_criticality.audit_summary if self.rust_criticality else None
            ),
        }


@dataclass(frozen=True)
class ChangeRiskReport:
    """Patch-level deterministic risk report for guarded workspace changes."""

    baseline_commit_sha: str
    patch_sha256: str
    files: tuple[FileRiskClassification, ...]
    report_reasons: tuple[ChangeRiskReason, ...] = ()

    @cached_property
    def overall_risk_level(self) -> RiskLevel:
        return _highest_risk(
            (
                *(file.risk_level for file in self.files),
                *(reason.risk_level for reason in self.report_reasons),
            ),
            default=RiskLevel.LOW,
        )

    @cached_property
    def changed_file_count(self) -> int:
        return len(self.files)

    @cached_property
    def risk_counts(self) -> dict[str, int]:
        counts = Counter(file.risk_level.value for file in self.files)
        return {level.value: counts.get(level.value, 0) for level in RiskLevel}

    @cached_property
    def audit_summary(self) -> dict[str, object]:
        return {
            "baseline_commit_sha": self.baseline_commit_sha,
            "patch_sha256": self.patch_sha256,
            "overall_risk_level": self.overall_risk_level.value,
            "changed_file_count": self.changed_file_count,
            "risk_counts": self.risk_counts,
            "files": tuple(file.audit_summary for file in self.files),
            "report_reasons": tuple(reason.audit_summary for reason in self.report_reasons),
        }


def classify_patch_risk(
    patch_diff: PatchDiff,
    *,
    validation_reasons: Iterable[ChangeRiskReason] = (),
    diff_limit_policy: DiffLimitPolicy = DEFAULT_DIFF_LIMIT_POLICY,
) -> ChangeRiskReport:
    """Classify each changed file in a guarded workspace patch."""

    added_lines_by_path = extract_added_lines_by_path(patch_diff.patch)
    files = tuple(
        _attach_criticality_shadow(
            classify_patch_file_risk(file_diff, added_lines_by_path=added_lines_by_path),
            _criticality_shadow_for_file(patch_diff, file_diff),
        )
        for file_diff in patch_diff.files
    )
    diff_limit_reasons = tuple(
        _from_diff_limit_reason(reason)
        for reason in evaluate_diff_limits(
            patch_diff,
            policy=diff_limit_policy,
        ).reasons
    )
    dependency_governance_reasons = _dependency_governance_reasons_for_patch(patch_diff)
    report_reasons = (
        *tuple(validation_reasons),
        *diff_limit_reasons,
        *dependency_governance_reasons,
    )

    return ChangeRiskReport(
        baseline_commit_sha=patch_diff.baseline_commit_sha,
        patch_sha256=patch_diff.patch_sha256,
        files=files,
        report_reasons=report_reasons,
    )


def _dependency_governance_reasons_for_patch(
    patch_diff: PatchDiff,
) -> tuple[ChangeRiskReason, ...]:
    plan = build_dependency_governance_plan(file_diff.path for file_diff in patch_diff.files)
    return _dependency_governance_reasons(plan)


def _dependency_governance_reasons(
    plan: DependencyGovernancePlan,
) -> tuple[ChangeRiskReason, ...]:
    if not plan.dependency_changes_detected:
        return ()

    return (
        _reason(
            "dependency-governance-required",
            _dependency_governance_risk_level(plan),
            (
                "Dependency governance checks are required before applying "
                "dependency-related changes."
            ),
            _dependency_governance_evidence(plan),
        ),
    )


def _dependency_governance_risk_level(plan: DependencyGovernancePlan) -> RiskLevel:
    approval_required = (
        plan.vulnerability_scan_required
        or plan.network_resolution_requires_approval
        or plan.private_registry_access_requires_approval
        or plan.new_dependency_tree_requires_approval
    )
    return RiskLevel.HIGH if approval_required else RiskLevel.MEDIUM


def _dependency_governance_evidence(
    plan: DependencyGovernancePlan,
) -> dict[str, object]:
    return {
        "workspace_count": len(plan.workspaces),
        "workspace_targets": tuple(
            _dependency_workspace_target_id(workspace) for workspace in plan.workspaces
        ),
        "manifest_count": sum(len(workspace.manifests) for workspace in plan.workspaces),
        "lockfile_count": sum(len(workspace.lockfiles) for workspace in plan.workspaces),
        "private_registry_config_count": sum(
            len(workspace.private_registry_configs) for workspace in plan.workspaces
        ),
        "resolver_environment_required": plan.resolver_environment_required,
        "resolver_environment_must_be_separate_from_host": (
            plan.resolver_environment_must_be_separate_from_host
        ),
        "resolver_environment_must_be_separate_from_runtime_workspace": (
            plan.resolver_environment_must_be_separate_from_runtime_workspace
        ),
        "shared_writable_cache_allowed": plan.shared_writable_cache_allowed,
        "per_run_writable_cache_allowed": plan.per_run_writable_cache_allowed,
        "shared_readonly_cache_requires_hash_verification": (
            plan.shared_readonly_cache_requires_hash_verification
        ),
        "transitive_dependency_delta_required": (plan.transitive_dependency_delta_required),
        "vulnerability_scan_required": plan.vulnerability_scan_required,
        "network_resolution_requires_approval": (plan.network_resolution_requires_approval),
        "private_registry_access_requires_approval": (
            plan.private_registry_access_requires_approval
        ),
        "new_dependency_tree_requires_approval": (plan.new_dependency_tree_requires_approval),
        "audit_secret_redaction_required": plan.audit_secret_redaction_required,
        "has_possible_manifest_lock_desync": plan.has_possible_manifest_lock_desync,
    }


def _dependency_workspace_target_id(workspace: WorkspaceDependencyTarget) -> str:
    directory = workspace.directory or "."
    return f"{directory}:{workspace.ecosystem.value}:{workspace.toolchain.value}"


def _attach_criticality_shadow(
    file_risk: FileRiskClassification,
    rust_criticality: RustCriticalityShadow,
) -> FileRiskClassification:
    bypass_reason = _criticality_bypass_risk_reason(rust_criticality)
    rust_reason = _rust_criticality_risk_reason(file_risk, rust_criticality)
    reasons = tuple(
        reason for reason in (*file_risk.reasons, bypass_reason, rust_reason) if reason is not None
    )
    risk_level = _highest_risk(reason.risk_level for reason in reasons)

    return FileRiskClassification(
        path=file_risk.path,
        old_path=file_risk.old_path,
        kind=file_risk.kind,
        risk_level=risk_level,
        reasons=reasons,
        additions=file_risk.additions,
        deletions=file_risk.deletions,
        binary=file_risk.binary,
        old_mode=file_risk.old_mode,
        new_mode=file_risk.new_mode,
        mode_changed=file_risk.mode_changed,
        rust_criticality=rust_criticality,
    )


def classify_patch_file_risk(
    file_diff: PatchFileDiff,
    *,
    added_lines_by_path: dict[str, tuple[str, ...]] | None = None,
) -> FileRiskClassification:
    """Classify one changed file from patch metadata and added lines."""

    path = normalize_repo_relative_path(file_diff.path)
    added_lines = (added_lines_by_path or {}).get(path, ())
    reasons = (
        *_path_risk_reasons(path),
        *_metadata_risk_reasons(file_diff),
        *_content_risk_reasons(path, added_lines),
    )

    if not reasons:
        reasons = (_baseline_path_reason(path),)

    risk_level = _highest_risk(reason.risk_level for reason in reasons)

    return FileRiskClassification(
        path=path,
        old_path=file_diff.old_path,
        kind=file_diff.kind,
        risk_level=risk_level,
        reasons=reasons,
        additions=file_diff.additions,
        deletions=file_diff.deletions,
        binary=file_diff.binary,
        old_mode=file_diff.old_mode,
        new_mode=file_diff.new_mode,
        mode_changed=file_diff.mode_changed,
    )


def _criticality_bypass_risk_reason(
    rust_criticality: RustCriticalityShadow,
) -> ChangeRiskReason | None:
    if rust_criticality.criticality_bypass_reason != BYPASS_REASON_LOCKFILE_INVALID_STRUCTURE:
        return None

    return _reason(
        BYPASS_REASON_LOCKFILE_INVALID_STRUCTURE,
        RiskLevel.HIGH,
        "Lockfile bypass claim failed structural validation before Rust analysis.",
        {
            "bypass_verdict": rust_criticality.criticality_bypass_verdict or "",
            "bypass_reason": rust_criticality.criticality_bypass_reason or "",
        },
    )


def _rust_criticality_risk_reason(
    file_risk: FileRiskClassification,
    rust_criticality: RustCriticalityShadow,
) -> ChangeRiskReason | None:
    if not rust_criticality.available:
        return None

    if rust_criticality.risk_level is None:
        return None

    if rust_criticality.criticality_index is None:
        return None

    if rust_criticality.criticality_index < MIN_ENFORCED_CRITICALITY_INDEX:
        return None

    rust_risk_level = RUST_CRITICALITY_ENFORCED_LEVELS.get(
        rust_criticality.risk_level.strip().lower()
    )
    if rust_risk_level is None:
        return None

    if RISK_LEVEL_ORDER[rust_risk_level] <= RISK_LEVEL_ORDER[file_risk.risk_level]:
        return None

    return _reason(
        "rust-criticality-signal",
        rust_risk_level,
        "Rust criticality analysis reported higher semantic or file risk.",
        {
            "path": file_risk.path,
            "criticality_index": rust_criticality.criticality_index,
            "rust_risk_level": rust_criticality.risk_level,
            "path_category": rust_criticality.path_category or "",
            "path_severity": rust_criticality.path_severity or "",
        },
    )


def _criticality_shadow_for_file(
    patch_diff: PatchDiff,
    file_diff: PatchFileDiff,
) -> RustCriticalityShadow:
    if _is_symlink_file(file_diff):
        return _criticality_failure_shadow(
            error_code="symlink-file",
            error_reason="Symlink entries are excluded from Rust criticality analysis",
        )

    if _is_git_submodule(file_diff):
        return _criticality_failure_shadow(
            error_code="git-submodule",
            error_reason="Git submodule entries are excluded from Rust criticality analysis",
        )

    if file_diff.binary:
        return _criticality_failure_shadow(
            error_code="binary-file",
            error_reason="binary files are excluded from Rust criticality shadow analysis",
        )

    if _is_jupyter_notebook(file_diff.path):
        return _criticality_failure_shadow(
            error_code="jupyter-notebook-unsupported",
            error_reason="Jupyter notebook files are excluded from Rust criticality analysis",
        )

    try:
        old_code, new_code = _load_criticality_file_contents(patch_diff, file_diff)
    except _CriticalityInvalidEncodingError:
        return _criticality_failure_shadow(
            error_code="invalid-encoding",
            error_reason="file contents are not valid UTF-8 for Rust criticality analysis",
        )
    except _CriticalityGitLfsPointerError:
        return _criticality_failure_shadow(
            error_code="git-lfs-pointer",
            error_reason="Git LFS pointer files are excluded from Rust criticality analysis",
        )
    except Exception as exc:
        return _criticality_failure_shadow(
            error_code="content-unavailable",
            error_reason=(
                f"file contents could not be loaded for Rust criticality shadow analysis: {exc}"
            ),
        )

    criticality_bypass_verdict = _evaluate_criticality_bypass_claim(
        file_diff.path,
        old_code,
        new_code,
    )
    if criticality_bypass_verdict.allowed:
        return _criticality_failure_shadow(
            criticality_bypass_verdict=criticality_bypass_verdict,
            error_code="criticality-bypass",
            error_reason=criticality_bypass_verdict.reason_code,
        )

    criticality_bypass_verdict = (
        criticality_bypass_verdict if criticality_bypass_verdict.is_candidate else None
    )

    if (
        _shadow_text_size_bytes(
            old_code.strip(),
            new_code.strip(),
        )
        > MAX_CRITICALITY_SHADOW_BYTES
    ):
        return _criticality_failure_shadow(
            criticality_bypass_verdict=criticality_bypass_verdict,
            error_code="file-too-large",
            error_reason="file size exceeds shadow mode criticality limits",
        )

    try:
        assessment = evaluate_criticality(
            RustCriticalityInput(
                file_path=normalize_repo_relative_path(file_diff.path),
                action_type=file_diff.kind.value,
                old_code=old_code,
                new_code=new_code,
                elevated=(
                    criticality_bypass_verdict is not None
                    and criticality_bypass_verdict.verdict == BYPASS_VERDICT_ELEVATED_RISK
                ),
            )
        )
    except Exception as exc:
        return _criticality_exception_shadow(
            exc,
            criticality_bypass_verdict=criticality_bypass_verdict,
        )

    return _criticality_success_shadow(
        assessment,
        criticality_bypass_verdict=criticality_bypass_verdict,
    )


def _is_symlink_file(file_diff: PatchFileDiff) -> bool:
    return file_diff.old_mode == GIT_SYMLINK_MODE or file_diff.new_mode == GIT_SYMLINK_MODE


def _is_git_submodule(file_diff: PatchFileDiff) -> bool:
    return file_diff.old_mode == GIT_SUBMODULE_MODE or file_diff.new_mode == GIT_SUBMODULE_MODE


def _is_jupyter_notebook(path: str) -> bool:
    return PurePosixPath(path).suffix.lower() in CRITICALITY_NOTEBOOK_EXTENSIONS


def _is_criticality_lockfile(path: str) -> bool:
    return PurePosixPath(path).name.lower() in CRITICALITY_LOCKFILE_NAMES


def _bypass_verdict(
    *,
    allowed: bool,
    reason_code: str,
    verdict: str,
    is_candidate: bool = True,
) -> CriticalityBypassVerdict:
    return CriticalityBypassVerdict(
        allowed=allowed,
        reason_code=reason_code,
        verdict=verdict,
        is_candidate=is_candidate,
    )


def _evaluate_criticality_bypass_claim(
    path: str,
    old_code: str,
    new_code: str,
    *,
    lockfile_allowlist: Iterable[str] = (),
) -> CriticalityBypassVerdict:
    normalized_path = normalize_repo_relative_path(path)

    lockfile_path_verdict = _is_valid_lockfile_bypass_path(
        normalized_path,
        allowlist=lockfile_allowlist,
    )
    if lockfile_path_verdict.allowed:
        return _validate_lockfile_snapshots(normalized_path, old_code, new_code)

    if lockfile_path_verdict.is_candidate:
        return lockfile_path_verdict

    return _is_valid_generated_bypass(normalized_path, old_code, new_code)


def _is_valid_lockfile_bypass_path(
    path: str,
    *,
    allowlist: Iterable[str] = (),
) -> CriticalityBypassVerdict:
    normalized_path = normalize_repo_relative_path(path)
    posix_path = PurePosixPath(normalized_path)
    lockfile_name = posix_path.name.lower()

    if lockfile_name not in CRITICALITY_LOCKFILE_NAMES:
        return _bypass_verdict(
            allowed=False,
            reason_code=BYPASS_REASON_NOT_CANDIDATE,
            verdict=BYPASS_VERDICT_RUST_INVOKED,
            is_candidate=False,
        )

    normalized_allowlist = {normalize_repo_relative_path(item).lower() for item in allowlist}

    if posix_path.parent == PurePosixPath(".") or (normalized_path.lower() in normalized_allowlist):
        return _bypass_verdict(
            allowed=True,
            reason_code=BYPASS_REASON_LOCKFILE_PATH_VALID,
            verdict=BYPASS_VERDICT_BYPASSED,
        )

    return _bypass_verdict(
        allowed=False,
        reason_code=BYPASS_REASON_LOCKFILE_NESTED_PATH,
        verdict=BYPASS_VERDICT_RUST_INVOKED,
    )


def _parse_json_object(content: str) -> dict[str, object] | None:
    try:
        parsed = json.loads(content)
    except json.JSONDecodeError:
        return None

    return parsed if isinstance(parsed, dict) else None


def _validate_json_lockfile(
    content: str,
    *,
    expected_keys: frozenset[str],
) -> CriticalityBypassVerdict:
    parsed = _parse_json_object(content)
    if parsed is None:
        return _bypass_verdict(
            allowed=False,
            reason_code=BYPASS_REASON_PARSE_FAILED_JSON,
            verdict=BYPASS_VERDICT_RUST_INVOKED,
        )

    if not expected_keys & parsed.keys():
        return _bypass_verdict(
            allowed=False,
            reason_code=BYPASS_REASON_SHAPE_MISMATCH_JSON,
            verdict=BYPASS_VERDICT_RUST_INVOKED,
        )

    return _bypass_verdict(
        allowed=True,
        reason_code=BYPASS_REASON_LOCKFILE_ROOT_VALID_JSON,
        verdict=BYPASS_VERDICT_BYPASSED,
    )


def _validate_package_lock(content: str) -> CriticalityBypassVerdict:
    return _validate_json_lockfile(
        content,
        expected_keys=frozenset({"lockfileVersion", "packages", "dependencies"}),
    )


def _validate_composer_lock(content: str) -> CriticalityBypassVerdict:
    return _validate_json_lockfile(
        content,
        expected_keys=frozenset({"packages", "packages-dev"}),
    )


def _validate_pipfile_lock(content: str) -> CriticalityBypassVerdict:
    return _validate_json_lockfile(
        content,
        expected_keys=frozenset({"_meta", "default", "develop"}),
    )


def _parse_toml_object(content: str) -> dict[str, object] | None:
    if tomllib is None:
        return None

    try:
        parsed = tomllib.loads(content)
    except tomllib.TOMLDecodeError:
        return None

    return parsed if isinstance(parsed, dict) else None


def _validate_toml_lockfile(
    content: str,
    *,
    expected_keys: frozenset[str],
) -> CriticalityBypassVerdict:
    parsed = _parse_toml_object(content)
    if parsed is None:
        return _bypass_verdict(
            allowed=False,
            reason_code=BYPASS_REASON_PARSE_FAILED_TOML,
            verdict=BYPASS_VERDICT_RUST_INVOKED,
        )

    if not expected_keys <= parsed.keys():
        return _bypass_verdict(
            allowed=False,
            reason_code=BYPASS_REASON_SHAPE_MISMATCH_TOML,
            verdict=BYPASS_VERDICT_RUST_INVOKED,
        )

    return _bypass_verdict(
        allowed=True,
        reason_code=BYPASS_REASON_LOCKFILE_ROOT_VALID_TOML,
        verdict=BYPASS_VERDICT_BYPASSED,
    )


def _validate_cargo_lock(content: str) -> CriticalityBypassVerdict:
    return _validate_toml_lockfile(
        content,
        expected_keys=frozenset({"package"}),
    )


def _validate_poetry_lock(content: str) -> CriticalityBypassVerdict:
    return _validate_toml_lockfile(
        content,
        expected_keys=frozenset({"package", "metadata"}),
    )


def _validate_uv_lock(content: str) -> CriticalityBypassVerdict:
    return _validate_toml_lockfile(
        content,
        expected_keys=frozenset({"package"}),
    )


CRITICALITY_LOCKFILE_VALIDATORS: dict[
    str,
    Callable[[str], CriticalityBypassVerdict],
] = {
    "cargo.lock": _validate_cargo_lock,
    "composer.lock": _validate_composer_lock,
    "package-lock.json": _validate_package_lock,
    "pipfile.lock": _validate_pipfile_lock,
    "poetry.lock": _validate_poetry_lock,
    "uv.lock": _validate_uv_lock,
}


def _validate_lockfile_structure(
    path: str,
    content: str,
) -> CriticalityBypassVerdict:
    validator = CRITICALITY_LOCKFILE_VALIDATORS.get(PurePosixPath(path).name.lower())
    if validator is None:
        return _bypass_verdict(
            allowed=False,
            reason_code=BYPASS_REASON_PARSE_FAILED_PATTERN,
            verdict=BYPASS_VERDICT_RUST_INVOKED,
        )

    return validator(content)


def _validate_lockfile_snapshots(
    path: str,
    old_code: str,
    new_code: str,
) -> CriticalityBypassVerdict:
    snapshots = tuple(code for code in (old_code, new_code) if code.strip())
    if not snapshots:
        return _bypass_verdict(
            allowed=False,
            reason_code=BYPASS_REASON_LOCKFILE_INVALID_STRUCTURE,
            verdict=BYPASS_VERDICT_ELEVATED_RISK,
        )

    for snapshot in snapshots:
        structure_verdict = _validate_lockfile_structure(path, snapshot)
        if not structure_verdict.allowed:
            return _bypass_verdict(
                allowed=False,
                reason_code=BYPASS_REASON_LOCKFILE_INVALID_STRUCTURE,
                verdict=BYPASS_VERDICT_ELEVATED_RISK,
            )

    return structure_verdict


def _is_valid_generated_bypass(
    path: str,
    old_code: str,
    new_code: str,
) -> CriticalityBypassVerdict:
    has_marker = _has_generated_file_marker(old_code, new_code)
    normalized_path = normalize_repo_relative_path(path).lower()
    posix_path = PurePosixPath(normalized_path)

    has_path_evidence = any(
        part in {"generated", "gen", "__generated__", "autogenerated"} for part in posix_path.parts
    ) or any(
        token in posix_path.name
        for token in (
            "generated",
            "autogenerated_",
            "_pb2.py",
            "_pb2_grpc.py",
            ".pb.",
            ".g.",
        )
    )

    if has_marker and has_path_evidence:
        return _bypass_verdict(
            allowed=True,
            reason_code=BYPASS_REASON_GENERATED_VALID,
            verdict=BYPASS_VERDICT_BYPASSED,
        )

    if has_marker:
        return _bypass_verdict(
            allowed=False,
            reason_code=BYPASS_REASON_GENERATED_MARKER_WITHOUT_PATH,
            verdict=BYPASS_VERDICT_RUST_INVOKED,
        )

    if has_path_evidence:
        return _bypass_verdict(
            allowed=False,
            reason_code=BYPASS_REASON_GENERATED_PATH_WITHOUT_MARKER,
            verdict=BYPASS_VERDICT_RUST_INVOKED,
        )

    return _bypass_verdict(
        allowed=False,
        reason_code=BYPASS_REASON_NOT_CANDIDATE,
        verdict=BYPASS_VERDICT_RUST_INVOKED,
        is_candidate=False,
    )


def _has_generated_file_marker(old_code: str, new_code: str) -> bool:
    return _has_generated_marker(old_code) or _has_generated_marker(new_code)


def _has_generated_marker(code: str) -> bool:
    first_lines = "\n".join(code.splitlines()[:5]).lower()
    return any(marker in first_lines for marker in CRITICALITY_GENERATED_MARKERS)


def _load_criticality_file_contents(
    patch_diff: PatchDiff,
    file_diff: PatchFileDiff,
) -> tuple[str, str]:
    workspace = Path(patch_diff.workspace_path).resolve()
    old_path = normalize_repo_relative_path(file_diff.old_path or file_diff.path)
    new_path = normalize_repo_relative_path(file_diff.path)

    old_size = 0
    new_size = 0

    if file_diff.kind not in {ChangedFileKind.ADDED, ChangedFileKind.UNTRACKED}:
        old_size = _baseline_file_size(
            workspace,
            patch_diff.baseline_commit_sha,
            old_path,
        )

    if file_diff.kind is not ChangedFileKind.DELETED:
        new_size = _workspace_file_size(workspace, new_path)

    if old_size + new_size > MAX_CRITICALITY_RAW_BYTES:
        return "x" * (MAX_CRITICALITY_SHADOW_BYTES + 1), ""

    old_code = ""
    new_code = ""

    if file_diff.kind not in {ChangedFileKind.ADDED, ChangedFileKind.UNTRACKED}:
        old_code = _read_baseline_file_text(
            workspace,
            patch_diff.baseline_commit_sha,
            old_path,
        )

    if file_diff.kind is not ChangedFileKind.DELETED:
        new_code = _read_workspace_file_text(workspace, new_path)

    return old_code, new_code


def _git_executable() -> str:
    git = shutil.which("git")
    if git is None:
        raise FileNotFoundError("git executable was not found on PATH")

    return git


def _baseline_file_size(workspace: Path, baseline_commit_sha: str, path: str) -> int:
    result = subprocess.run(  # nosec B603
        [_git_executable(), "cat-file", "-s", f"{baseline_commit_sha}:{path}"],
        cwd=workspace,
        check=True,
        capture_output=True,
        text=True,
    )
    return int(result.stdout.strip())


def _workspace_file_size(workspace: Path, path: str) -> int:
    return (workspace / path).stat().st_size


def _read_baseline_file_text(
    workspace: Path,
    baseline_commit_sha: str,
    path: str,
) -> str:
    result = subprocess.run(  # nosec B603
        [_git_executable(), "show", f"{baseline_commit_sha}:{path}"],
        cwd=workspace,
        check=True,
        capture_output=True,
    )
    return _decode_criticality_file_bytes(result.stdout)


def _read_workspace_file_text(workspace: Path, path: str) -> str:
    return _decode_criticality_file_bytes((workspace / path).read_bytes())


def _decode_criticality_file_bytes(raw_content: bytes) -> str:
    if raw_content.startswith(GIT_LFS_POINTER_PREFIX):
        raise _CriticalityGitLfsPointerError

    try:
        return raw_content.decode("utf-8", errors="strict")
    except UnicodeDecodeError as exc:
        raise _CriticalityInvalidEncodingError from exc


def _shadow_text_size_bytes(*values: str) -> int:
    return sum(len(value.encode("utf-8", errors="ignore")) for value in values)


def _criticality_success_shadow(
    assessment: RustCriticalityAssessment,
    *,
    criticality_bypass_verdict: CriticalityBypassVerdict | None = None,
) -> RustCriticalityShadow:
    metrics = assessment.semantic_metrics
    return RustCriticalityShadow(
        available=True,
        criticality_index=assessment.criticality_index,
        risk_level=assessment.risk_level,
        reasons=assessment.reasons,
        semantic_metrics={
            "old_node_count": metrics.old_node_count,
            "new_node_count": metrics.new_node_count,
            "old_token_count": metrics.old_token_count,
            "new_token_count": metrics.new_token_count,
            "matched_node_count": metrics.matched_node_count,
            "survival_ratio": metrics.survival_ratio,
        },
        path_category=assessment.path_category,
        path_severity=assessment.path_severity,
        criticality_bypass_verdict=(
            criticality_bypass_verdict.verdict if criticality_bypass_verdict else None
        ),
        criticality_bypass_reason=(
            criticality_bypass_verdict.reason_code if criticality_bypass_verdict else None
        ),
    )


def _criticality_failure_shadow(
    *,
    error_code: str,
    error_reason: str,
    criticality_bypass_verdict: CriticalityBypassVerdict | None = None,
) -> RustCriticalityShadow:
    return RustCriticalityShadow(
        available=False,
        error_code=error_code,
        error_reason=error_reason,
        criticality_bypass_verdict=(
            criticality_bypass_verdict.verdict if criticality_bypass_verdict else None
        ),
        criticality_bypass_reason=(
            criticality_bypass_verdict.reason_code if criticality_bypass_verdict else None
        ),
    )


def _criticality_exception_shadow(
    exc: Exception,
    *,
    criticality_bypass_verdict: CriticalityBypassVerdict | None = None,
) -> RustCriticalityShadow:
    if isinstance(exc, RustKernelUnavailableError):
        return _criticality_failure_shadow(
            criticality_bypass_verdict=criticality_bypass_verdict,
            error_code="rust-kernel-unavailable",
            error_reason=str(exc),
        )

    if isinstance(exc, RustCriticalityEvaluationError):
        return _criticality_failure_shadow(
            criticality_bypass_verdict=criticality_bypass_verdict,
            error_code=exc.error_code,
            error_reason=exc.reason,
        )

    if isinstance(exc, RustKernelError):
        return _criticality_failure_shadow(
            criticality_bypass_verdict=criticality_bypass_verdict,
            error_code="rust-kernel-error",
            error_reason=str(exc),
        )

    return _criticality_failure_shadow(
        criticality_bypass_verdict=criticality_bypass_verdict,
        error_code="rust-criticality-unexpected-error",
        error_reason=str(exc),
    )


def extract_added_lines_by_path(patch: str) -> dict[str, tuple[str, ...]]:
    """Extract added content lines from a unified Git patch without diff headers."""

    added_lines: dict[str, list[str]] = {}
    current_path: str | None = None

    for line in patch.splitlines():
        if line.startswith("diff --git "):
            current_path = None
            continue

        if line.startswith("+++ "):
            current_path = _parse_new_patch_path(line[4:].strip())
            if current_path is not None:
                added_lines.setdefault(current_path, [])
            continue

        if current_path is None:
            continue

        if line.startswith("+") and not line.startswith("+++"):
            added_lines[current_path].append(line[1:])

    return {path: tuple(lines) for path, lines in added_lines.items()}


def _path_risk_reasons(path: str) -> tuple[ChangeRiskReason, ...]:
    reasons: list[ChangeRiskReason] = []
    lower_path = path.lower()

    if _matches_any(lower_path, SECURITY_SENSITIVE_PATH_PATTERNS):
        reasons.append(
            _reason(
                "security-sensitive-path",
                RiskLevel.CRITICAL,
                "File path indicates credential, key, secret, or environment material.",
                {"path": path},
            )
        )

    if _matches_name(lower_path, DEPENDENCY_FILE_NAMES) or _matches_name_pattern(
        lower_path, DEPENDENCY_NAME_PATTERNS
    ):
        reasons.append(
            _reason(
                "dependency-file-change",
                RiskLevel.HIGH,
                "Dependency manifest or lockfile changed.",
                {"path": path},
            )
        )

    if _matches_any(lower_path, CI_PATH_PATTERNS):
        reasons.append(
            _reason(
                "ci-config-change",
                RiskLevel.HIGH,
                "CI/CD workflow or pipeline configuration changed.",
                {"path": path},
            )
        )

    if _matches_any(lower_path, INFRA_PATH_PATTERNS) or _has_any_segment(
        lower_path, DEPLOY_PATH_SEGMENTS
    ):
        reasons.append(
            _reason(
                "infrastructure-or-deploy-change",
                RiskLevel.HIGH,
                "Infrastructure, container, deployment, or release configuration changed.",
                {"path": path},
            )
        )

    if _has_any_segment(lower_path, AUTH_SECURITY_PATH_SEGMENTS):
        reasons.append(
            _reason(
                "auth-security-path-change",
                RiskLevel.HIGH,
                "Authentication, authorization, session, or security-sensitive code path changed.",
                {"path": path},
            )
        )

    if _is_script_like_path(lower_path):
        reasons.append(
            _reason(
                "script-change",
                RiskLevel.HIGH,
                "Executable script or automation path changed.",
                {"path": path},
            )
        )

    return tuple(reasons)


def _metadata_risk_reasons(file_diff: PatchFileDiff) -> tuple[ChangeRiskReason, ...]:
    reasons: list[ChangeRiskReason] = []
    path = file_diff.path

    if file_diff.binary:
        reasons.append(
            _reason(
                "binary-file-change",
                RiskLevel.HIGH,
                "Binary file changed and cannot be reviewed as plain text.",
                {"path": path},
            )
        )

    if file_diff.old_mode == "120000" or file_diff.new_mode == "120000":
        reasons.append(
            _reason(
                "symlink-change",
                RiskLevel.CRITICAL,
                "Symlink changes can alter filesystem boundaries.",
                {"path": path},
            )
        )
    elif file_diff.mode_changed:
        reasons.append(
            _reason(
                "file-mode-change",
                RiskLevel.HIGH,
                "File mode changed, which may alter executability or access behavior.",
                {
                    "path": path,
                    "old_mode": file_diff.old_mode or "",
                    "new_mode": file_diff.new_mode or "",
                },
            )
        )

    if _extension(path.lower()) in BINARY_EXTENSIONS:
        reasons.append(
            _reason(
                "generated-executable-artifact",
                RiskLevel.HIGH,
                "Generated executable or compiled artifact changed.",
                {"path": path},
            )
        )

    return tuple(reasons)


def _content_risk_reasons(
    path: str,
    added_lines: tuple[str, ...],
) -> tuple[ChangeRiskReason, ...]:
    reasons: list[ChangeRiskReason] = []
    seen_codes: set[str] = set()

    for line in added_lines:
        for code, pattern in SECRET_ADDED_LINE_PATTERNS:
            if code in seen_codes or not pattern.search(line):
                continue

            seen_codes.add(code)
            reasons.append(
                _reason(
                    f"added-secret-{code}",
                    RiskLevel.CRITICAL,
                    "Added line appears to contain credential or secret material.",
                    {"path": path, "pattern": code},
                )
            )

        for code, pattern in DESTRUCTIVE_ADDED_LINE_PATTERNS:
            if code in seen_codes or not pattern.search(line):
                continue

            seen_codes.add(code)
            risk_level = RiskLevel.CRITICAL if _is_script_like_path(path) else RiskLevel.HIGH
            reasons.append(
                _reason(
                    f"destructive-command-{code}",
                    risk_level,
                    "Added line appears to contain a destructive command pattern.",
                    {"path": path, "pattern": code},
                )
            )

    return tuple(reasons)


def _baseline_path_reason(path: str) -> ChangeRiskReason:
    lower_path = path.lower()

    if _is_documentation_path(lower_path):
        return _reason(
            "documentation-change",
            RiskLevel.LOW,
            "Documentation-only path changed.",
            {"path": path},
        )

    if _is_test_path(lower_path):
        return _reason(
            "test-change",
            RiskLevel.LOW,
            "Test path changed without privileged file indicators.",
            {"path": path},
        )

    if _extension(lower_path) in SOURCE_EXTENSIONS:
        return _reason(
            "source-code-change",
            RiskLevel.MEDIUM,
            "Source code changed.",
            {"path": path},
        )

    return _reason(
        "project-file-change",
        RiskLevel.MEDIUM,
        "Project file changed without a lower-risk classification.",
        {"path": path},
    )


def _parse_new_patch_path(raw_path: str) -> str | None:
    if raw_path == "/dev/null":
        return None

    path = raw_path[2:] if raw_path.startswith("b/") else raw_path
    return normalize_repo_relative_path(path)


def _from_diff_limit_reason(reason: DiffLimitReason) -> ChangeRiskReason:
    return _reason(
        reason.code,
        reason.risk_level,
        reason.reason,
        dict(reason.evidence),
    )


def _reason(
    code: str,
    risk_level: RiskLevel,
    reason: str,
    evidence: dict[str, object],
) -> ChangeRiskReason:
    return ChangeRiskReason(
        code=code,
        risk_level=risk_level,
        reason=reason,
        evidence=tuple(sorted(evidence.items())),
    )


def _highest_risk(
    risk_levels: Iterable[RiskLevel],
    *,
    default: RiskLevel = RiskLevel.LOW,
) -> RiskLevel:
    highest = default

    for risk_level in risk_levels:
        if RISK_LEVEL_ORDER[risk_level] > RISK_LEVEL_ORDER[highest]:
            highest = risk_level

    return highest


def _matches_any(path: str, patterns: Iterable[str]) -> bool:
    return any(fnmatch.fnmatchcase(path, pattern) for pattern in patterns)


def _matches_name(path: str, names: set[str]) -> bool:
    return PurePosixPath(path).name in names


def _matches_name_pattern(path: str, patterns: Iterable[str]) -> bool:
    name = PurePosixPath(path).name
    return any(fnmatch.fnmatchcase(name, pattern) for pattern in patterns)


def _has_any_segment(path: str, segments: set[str]) -> bool:
    return any(segment in segments for segment in path.split("/"))


def _extension(path: str) -> str:
    return PurePosixPath(path).suffix.lower()


def _is_script_like_path(path: str) -> bool:
    return (
        _extension(path) in SCRIPT_EXTENSIONS
        or _has_any_segment(path, SCRIPT_PATH_SEGMENTS)
        or PurePosixPath(path).name in {"makefile", "dockerfile"}
    )


def _is_documentation_path(path: str) -> bool:
    name = PurePosixPath(path).name
    stem = PurePosixPath(path).stem
    return (
        path.startswith("docs/")
        or _extension(path) in DOC_EXTENSIONS
        or name in {"license", "notice"}
        or stem in DOC_FILE_NAMES
    )


def _is_test_path(path: str) -> bool:
    name = PurePosixPath(path).name
    stem = PurePosixPath(path).stem
    return (
        path.startswith("tests/")
        or path.startswith("test/")
        or "/tests/" in path
        or name.startswith("test_")
        or stem.endswith("_test")
    )


__all__ = [
    "ChangeRiskClassificationError",
    "ChangeRiskReason",
    "ChangeRiskReport",
    "FileRiskClassification",
    "CRITICALITY_GENERATED_MARKERS",
    "CRITICALITY_LOCKFILE_NAMES",
    "CRITICALITY_NOTEBOOK_EXTENSIONS",
    "GIT_LFS_POINTER_PREFIX",
    "GIT_SUBMODULE_MODE",
    "GIT_SYMLINK_MODE",
    "MAX_CRITICALITY_RAW_BYTES",
    "MAX_CRITICALITY_SHADOW_BYTES",
    "MIN_ENFORCED_CRITICALITY_INDEX",
    "RISK_LEVEL_ORDER",
    "RUST_CRITICALITY_ENFORCED_LEVELS",
    "RustCriticalityShadow",
    "classify_patch_file_risk",
    "classify_patch_risk",
    "extract_added_lines_by_path",
]
